table: "/home/grahman/projects/qadabra/workflow/data/table.biom"
metadata: "/home/grahman/projects/qadabra/workflow/data/metadata.tsv"
model:
    covariate: sex
    target: F
    reference: M
songbird_params:
    epochs: 5000
    differential_prior: 1
