table: "/home/grahman/projects/xebec/xebec/tests/data/table.biom"
metadata: "/home/grahman/projects/xebec/xebec/tests/data/metadata.tsv"
model:
    covariate: anemia
    target: anemic
    reference: normal
songbird_params:
    epochs: 5000
    differential_prior: 1
log_ratio_feat_pcts:
    - 1
    - 5
    - 10
    - 15
    - 20
ml_params:
    n_splits: 10
    n_repeats: 5
