# github.com/snakemake-workflows/dna-seq-varlociraptor/blob/master/.github/workflows/main.yml
name: "Main CI"

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "README.md"
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "README.md"

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        stagein: "mamba install -y -n snakemake --channel conda-forge --channel bioconda"
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Linting
    steps:
    - uses: actions/checkout@v2

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend mamba"
        stagein: |
            pip install -e .
            conda config --get channel_priority --json
            qadabra add-dataset --table data/table.biom --metadata data/metadata.tsv --name beep --factor-name anemia --target-level anemic --reference-level normal --dataset-sheet config/datasets.tsv

    - name: Test report
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--report report.zip"
