# github.com/snakemake-workflows/dna-seq-varlociraptor/blob/master/.github/workflows/main.yml
name: "Main CI"

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "README.md"
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: qadabra
          mamba-version: "*"
          channels: conda-forge,defaults,bioconda
          channel-priority: true
          python-version: "3.9"

      - name: Install conda packages
        shell: bash -l {0}
        run: mamba install snakemake click biom-format pandas numpy cython

      - name: Install pip packages
        shell: bash -l {0}
        run: pip install iow

      - name: Install qadabra
        shell: bash -l {0}
        run: pip install -e .

      - name: Run Snakemake
        shell: bash -l {0}
        run: make snaketest
